name: Coords
main: kenygamer\Coords\Coords
version: 1.0.2-beta
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]

author: kenygamer
description: A PocketMine-MP plugin to see your or someone else's coordinates

commands:
 coords:
  description: See your or someone else's coordinates.
  usage: "/coords [player]"
  
permissions:
 coords:
  description: Allows access to all Coords features.
  default: false
  children:
   coords.command:
    description: Allows access to all Coords commands.
    default: false
    children:
     coords.command.coords:
      description: Allows access to the coords command.
      default: op
      children:
       coords.command.coords.others:
        description: "Permission to see someone else's coordinates."
        default: op
